### ISSUE TITLE
Nokogiri Xml Erro

### ISSUE THREAD

**Issue by sunilkalyan08** [biola/rack-cas#43] opened 2015-07-30 13:26 UTC
```
Nokogiri::XML::XPath::SyntaxError
Undefined namespace prefix: /cas:serviceResponse/cas:authenticationSuccess
```
I am getting these when redirecting to client after authentication from client

server console log:
```
method=POST path=/login format=html controller=casino/sessions action=create status=303 duration=184.19 view=0.00 db=45.24 location=http://localhost:3000/?ticket=ST-14382625833483-xJuAH6G9SXSShNaqGObC8ZpshPFT4vVR6PQzlPFu params={"utf8"=>"✓", "authenticity_token"=>"EqmB55XUTUghYxsemXP3nZPadkaQCcnSqxxdhJyblfPrDsnMw4S17As+axDJoFX0XaC4aJIq36+atYSLFvt6IQ==", "lt"=>"LT-14382625688311-0ymCWT6EkVrHlFww8qfdY3m4aZOIiiDsWiUtLqdY", "service"=>"http://localhost:3000/", "username"=>"superadmin@gmail.com", "password"=>"[FILTERED]", "button"=>""}
DEBUG: Chewy strategies stack: [2] -> atomic @ /home/.rvm/gems/ruby-2.1.5@vakilsearch/gems/chewy-0.8.1/lib/chewy/railtie.rb:16
DEBUG: Chewy strategies stack: [2] <- atomic @ /home/.rvm/gems/ruby-2.1.5@vakilsearch/gems/chewy-0.8.1/lib/chewy/railtie.rb:16
method=GET path=/serviceValidate format=*/* controller=casino/service_tickets action=service_validate status=302 duration=0.69 view=0.00 db=0.00 location=http://localhost:3001/login params={"service"=>"http://localhost:3000/", "ticket"=>"ST-14382625833483-xJuAH6G9SXSShNaqGObC8ZpshPFT4vVR6PQzlPFu"}
```

**Comment by trkrameshkumar** [comment] 2015-07-31 04:36
+1 Any solution for this issue?

**Comment by jabbajac** [comment] 2015-08-17 01:57
+1 I'm also running into the same issue

**Comment by adamcrown** [comment] 2015-10-08 03:57
Sorry it's taken me so long to jump in on this. I've been busy with other projects recently.

@sunilkalyan08, it looks like you're using Casino. @trkrameshkumar and @jabbajac are you also using Casino?

I've been using Casino myself for my local development and haven't had any problems like this so far. I may need to know your Nokogiri version and maybe even a dump of the XML response but I'll let you know for sure after I've had some time to look into this further.

**Comment by adamcrown** [comment] 2015-10-08 09:53
I tried this out with the newest version of Casino and Nokogiri and I'm not seeing any problems or any reason the XML namespace shouldn't be valid.

Could somebody who is having this problem follow the steps below to post the XML they're getting back from their server?

- Clone `git@github.com:biola/rack-cas.git`
- Replace the `gem 'rack-cas'` line in your `Gemfile` with `gem 'rack-cas', path: '../rack-cas'`
- Add `gem 'pry'` to your `Gemfile`
- Do a `bundle install`
- Restart your server
- Add `require 'pry'; binding.pry` to the top of the `extra_attributes` method in `lib/rack-cas/service_validation_response.rb`
- Call `puts response.body` in the pry session and post the result.

Thanks.

**Comment by jabbajac** [comment] 2015-10-08 13:24
@adamcrown Not using Casino, but it was a misconfiguration on my end. I don't remember what it was though unfortunately.

**Comment by trkrameshkumar** [comment] 2015-10-08 15:55
@adamcrown we were using casino, but after some time our project requirement got changed, so we give up on that , Anyway thanks for your reply.

**Comment by mikestephens** [comment] 2015-10-08 16:16
So it looks like it can't be reproduced / no longer necessary. If anyone still has this issue feel free to open this back up, but for now I am going to close it.

**Closed by mikestephens** 2015-10-08 16:16 UTC

**Comment by adamcrown** [comment] 2015-10-09 01:18
I'm guessing some sort of non-CAS response was being produced by the CAS server. Maybe a 500 error or something. That would cause this sort of error to happen.
